### ISSUE TITLE
Tag组件默认字体大小太小，建议默认大一些。

### ISSUE THREAD

**Issue by Gaius-98** [Yirujet/canvas-like-html#1]
![V8S4KX~KX)K`1XDPLWKU}2N](https://github.com/Yirujet/canvas-like-html/assets/59641156/dfd4ab49-ee46-4ce1-a00d-b247abb4c690)
![GUIH4{K{F@O9H4(59 V2Z7](https://github.com/Yirujet/canvas-like-html/assets/59641156/81f339d7-be7c-48ea-94c0-b8b45500bcc7)

**Comment by Yirujet** [comment]
CanvasLikeHtml在实例化时，传入globalProps属性，如：new CanvasLikeHtml({ globalProps: { fontSize: 14 } })，可修改绘图上下文对象中的字体大小
